const LOAD_ACTIONS = [
  'LOADING',
  'LOADED',
  'LOAD_FAILURE',
];
const POST_LOAD_ACTIONS = [
  'POST_LOADING',
  'POST_LOADED',
  'POST_LOAD_FAILURE',
];
const PROMISE = 'PROMISE';
const POST_LOAD_PROMISE = 'POST_LOAD_PROMISE';
const ISSUES_PREFIX = 'ISSUES_';
const REPOS_PREFIX = 'REPOS_';
const PREFIX_ISSUE = 'ISSUE_';
const VALIDATE_FORM = 'VALIDATE_FORM';
const SET_HEADERS = 'SET_HEADERS';
const CHANGE_PARAMS = 'CHANGE_PARAMS';
const PER_PAGE_LIST = [10, 30, 45, 60, 75, 100];

export {
  POST_LOAD_PROMISE,
  POST_LOAD_ACTIONS,
  PER_PAGE_LIST,
  CHANGE_PARAMS,
  SET_HEADERS,
  LOAD_ACTIONS,
  PROMISE,
  ISSUES_PREFIX,
  REPOS_PREFIX,
  PREFIX_ISSUE,
  VALIDATE_FORM,
};
