const LOAD_ACTIONS = ['LOADING', 'LOADED', 'LOAD_FAILURE'];
const PROMISE = 'PROMISE';
const ISSUES_PREFIX = 'ISSUES_';
const PREFIX_ISSUE = 'ISSUE_';
const VALIDATE_FORM = 'VALIDATE_FORM';

export { LOAD_ACTIONS, PROMISE, ISSUES_PREFIX, PREFIX_ISSUE, VALIDATE_FORM };
